[package]
name = "gui"
version = "0.5.0"
edition = "2021"
default-run = "ntsc-rs-standalone"
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntscrs = { path = "../ntscrs" }
eframe = { version = "0.26", features=["persistence"] }
env_logger = "0.10.0"
image = "0.24.7"
snafu = "0.7.5"
logos = "0.13"
gstreamer = "0.21"
gstreamer-base = "0.21"
gstreamer-video = "0.21"
gstreamer-controller = "0.21"
futures-lite = "2.2.0"
async-executor = "1.5.1"
async-task = "4.7.0"
waker-fn = "1.1.0"
log = "0.4.20"
rfd = "0.12.1"
rand = "0.8.5"

[build-dependencies]
embed-resource = "2.4"

[[bin]]
name = "ntsc-rs-standalone"

[[bin]]
name = "ntsc-rs-launcher"
