[package]
name = "gui"
version = "0.2.1"
edition = "2021"
default-run = "ntsc-rs-standalone"
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntscrs = { path = "../ntscrs" }
eframe = { version = "0.24.1", features=["persistence"] }
env_logger = "0.10.0"
image = "0.24.7"
snafu = "0.7.5"
logos = "0.13"
gstreamer = "0.21.0"
gstreamer-base = "0.21.0"
gstreamer-video = "0.21.0"
gstreamer-controller = "0.21.0"
futures-lite = "2.1.0"
async-executor = "1.5.1"
async-task = "4.4.0"
waker-fn = "1.1.0"
log = "0.4.20"
rfd = "0.12.1"

[build-dependencies]
embed-resource = "2.4"

[[bin]]
name = "ntsc-rs-standalone"

[[bin]]
name = "ntsc-rs-launcher"
