[package]
name = "openfx-plugin"
version = "0.1.0"
edition = "2021"
license = "MIT OR ISC OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntscrs = { path = "../ntscrs" }

[build-dependencies]
bindgen = "0.66.1"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "build-plugin"