[package]
name = "ntscrs-c-api"
version = "0.1.0"
edition = "2021"
license = "MIT OR ISC OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
ntscrs = { path = "../ntscrs" }