[package]
name = "ntscrs-c-api"
version = "0.1.0"
edition = "2021"
license = "MIT OR ISC OR Apache-2.0"
repository = "https://github.com/valadaptive/ntsc-rs/tree/main/crates/c-api"

[lib]
crate-type = ["staticlib"]

[dependencies]
ntscrs = { path = "../ntscrs" }
paste = "1.0"