name: Build Workspace

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install gstreamer (Linux)
      run: |
        sudo apt-get install libgstreamer1.0-dev -y
      if: ${{ matrix.os == 'ubuntu-20.04' }}
    - name: Build
      run: cargo build --release --workspace
